// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var SERVICES = [
  {
    id: "focus-custom",
    name: "Focus Custom \u2014 Software Sob Medida",
    url: "https://focusinteligente.com.br/solucoes-sob-medida",
    positioning: "Lovable Partner Oficial",
    pricing: "Valor sob consulta (projeto fechado, 50% assinatura + 50% entrega)",
    description: "Desenvolvimento de sistemas exclusivos (dashboards, CRMs, portais, ERPs, agentes de IA, playbooks) constru\xEDdos sobre a Lovable, adaptados 100% \xE0 opera\xE7\xE3o do cliente.",
    idealFor: "Ag\xEAncias, consultorias e prestadores de servi\xE7o com processos \xFAnicos que nenhum SaaS gen\xE9rico atende."
  },
  {
    id: "hub-empresarial",
    name: "Hub Empresarial \u2014 Plataforma SaaS",
    url: "https://focusinteligente.com.br/hub-empresarial",
    pricing: "Plus R$ 119/m\xEAs \xB7 Pro R$ 249/m\xEAs",
    description: "Plataforma pronta com CRM, financeiro, projetos, dashboards, RH e automa\xE7\xF5es. Acesso imediato.",
    idealFor: "PMEs que precisam sair de planilhas e WhatsApp com solu\xE7\xE3o completa e imediata."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List Focus services",
  description: "List Focus Gest\xE3o's services (Focus Custom sob medida e Hub Empresarial SaaS) with positioning, pricing and target audience.",
  inputSchema: {
    id: z.enum(["focus-custom", "hub-empresarial"]).optional().describe("Optional service id to return only one service.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const items = id ? SERVICES.filter((s) => s.id === id) : SERVICES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/search-blog.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var SITE = "https://focusinteligente.com.br";
var POSTS = [
  { slug: "poder-do-notion-empresas-produtivas", title: "O poder do Notion em empresas produtivas", tags: ["notion", "produtividade", "empresas"] },
  { slug: "mapeamento-processos-crescimento", title: "Mapeamento de processos para crescimento", tags: ["processos", "gestao"] },
  { slug: "5-erros-produtividade", title: "5 erros de produtividade", tags: ["produtividade", "erros"] },
  { slug: "gestao-projetos-notion", title: "Gest\xE3o de projetos", tags: ["projetos", "gestao"] },
  { slug: "sistema-completo-notion-automacao", title: "Sistema completo com automa\xE7\xE3o", tags: ["sistema", "automacao"] },
  { slug: "matriz-eisenhower", title: "Matriz de Eisenhower", tags: ["priorizacao", "metodos"] },
  { slug: "metodo-gtd-guia", title: "M\xE9todo GTD \u2014 Guia completo", tags: ["gtd", "metodos", "produtividade"] },
  { slug: "tecnica-pomodoro-guia", title: "T\xE9cnica Pomodoro \u2014 Guia", tags: ["pomodoro", "foco"] },
  { slug: "planejamento-semanal-passo-a-passo", title: "Planejamento semanal passo a passo", tags: ["planejamento", "semanal"] },
  { slug: "planejamento-mensal-sistema", title: "Sistema de planejamento mensal", tags: ["planejamento", "mensal"] },
  { slug: "planejamento-anual-do-zero", title: "Planejamento anual do zero", tags: ["planejamento", "anual"] },
  { slug: "reunioes-produtivas", title: "Reuni\xF5es produtivas", tags: ["reunioes", "gestao"] },
  { slug: "ia-pmes-automatizar-processos", title: "IA para PMEs automatizarem processos", tags: ["ia", "pmes", "automacao"] },
  { slug: "mapeamento-processos-agencias", title: "Mapeamento de processos para ag\xEAncias", tags: ["agencias", "processos"] },
  { slug: "notion-agencias-guia-2026", title: "Notion para ag\xEAncias \u2014 Guia 2026", tags: ["notion", "agencias"] },
  { slug: "150-sistemas-notion", title: "150 sistemas em Notion", tags: ["notion", "sistemas"] },
  { slug: "notion-vs-planilhas", title: "Notion vs Planilhas", tags: ["notion", "planilhas"] },
  { slug: "rotina-matinal-poderosa", title: "Rotina matinal poderosa", tags: ["rotina", "habitos"] },
  { slug: "metas-inteligentes-smart", title: "Metas inteligentes SMART", tags: ["metas", "smart"] },
  { slug: "organizar-tarefas-dia-a-dia", title: "Organizar tarefas do dia a dia", tags: ["tarefas", "organizacao"] },
  { slug: "gestao-tempo-quem-vive-ocupado", title: "Gest\xE3o de tempo para quem vive ocupado", tags: ["tempo", "gestao"] },
  { slug: "checklist-diario-produtividade", title: "Checklist di\xE1rio de produtividade", tags: ["checklist", "produtividade"] }
];
var search_blog_default = defineTool2({
  name: "search_blog",
  title: "Search Focus blog",
  description: "Search Focus Gest\xE3o's blog by keyword against titles, slugs and tags. Returns matching posts with absolute URLs.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Keyword (e.g. 'notion', 'produtividade', 'gtd')."),
    limit: z2.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    const max = limit ?? 10;
    const results = POSTS.filter(
      (p) => p.slug.includes(q) || p.title.toLowerCase().includes(q) || p.tags.some((t) => t.includes(q))
    ).slice(0, max).map((p) => ({ title: p.title, url: `${SITE}/blog/${p.slug}`, tags: p.tags }));
    return {
      content: [
        {
          type: "text",
          text: results.length === 0 ? `Nenhum artigo encontrado para "${query}".` : JSON.stringify(results, null, 2)
        }
      ],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get Focus contact info",
  description: "Return canonical contact channels and key URLs for Focus Gest\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Focus Gest\xE3o",
      positioning: "Lovable Partner Oficial",
      site: "https://focusinteligente.com.br",
      about: "https://focusinteligente.com.br/sobre",
      helpCenter: "https://focusinteligente.com.br/central-ajuda",
      services: {
        focusCustom: "https://focusinteligente.com.br/solucoes-sob-medida",
        hubEmpresarial: "https://focusinteligente.com.br/hub-empresarial"
      },
      billing: "Consultoria por projeto fechado (valor sob consulta)."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqhpxqccsrgbdmsknppj";
var mcp_default = defineMcp({
  name: "focus-gestao-mcp",
  title: "Focus Gest\xE3o MCP",
  version: "0.1.0",
  instructions: "Tools to explore Focus Gest\xE3o (Lovable Partner Oficial): list services (Focus Custom sob medida e Hub Empresarial SaaS), search blog articles, and retrieve official contact URLs. Requires OAuth sign-in.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, search_blog_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
