// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var SERVICES = [
  {
    id: "focus-custom",
    name: "Focus Custom \u2014 Software Sob Medida",
    url: "https://focusinteligente.com.br/solucoes-sob-medida",
    positioning: "Lovable Partner Oficial",
    pricing: "Valor sob consulta (projeto fechado, 50% assinatura + 50% entrega)",
    description: "Desenvolvimento de sistemas exclusivos (dashboards, CRMs, portais, ERPs, agentes de IA, playbooks) constru\xEDdos sobre a Lovable, adaptados 100% \xE0 opera\xE7\xE3o do cliente.",
    idealFor: "Ag\xEAncias, consultorias e prestadores de servi\xE7o com processos \xFAnicos que nenhum SaaS gen\xE9rico atende."
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List Focus services",
  description: "List Focus Gest\xE3o's services (Focus Custom sob medida) with positioning, pricing and target audience.",
  inputSchema: {
    id: z.enum(["focus-custom"]).optional().describe("Optional service id to return only one service.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const items = id ? SERVICES.filter((s) => s.id === id) : SERVICES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get Focus contact info",
  description: "Return canonical contact channels and key URLs for Focus Gest\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Focus Gest\xE3o",
      positioning: "Lovable Partner Oficial",
      site: "https://focusinteligente.com.br",
      about: "https://focusinteligente.com.br/sobre",
      helpCenter: "https://focusinteligente.com.br/central-ajuda",
      services: {
        focusCustom: "https://focusinteligente.com.br/solucoes-sob-medida"
      },
      billing: "Consultoria por projeto fechado (valor sob consulta)."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pqhpxqccsrgbdmsknppj";
var mcp_default = defineMcp({
  name: "focus-gestao-mcp",
  title: "Focus Gest\xE3o MCP",
  version: "0.1.0",
  instructions: "Tools to explore Focus Gest\xE3o (Lovable Partner Oficial): list services (Focus Custom sob medida) and retrieve official contact URLs. Requires OAuth sign-in.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
